version: '3.7'

services:

  webapi:
    build:
      context: ./services/webapp
      dockerfile: Dockerfile-dev
    volumes:
      - './services/webapp:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@webapi-db:5432/webapi_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@webapi-db:5432/webapi_test
    depends_on: 
      - webapi-db
  
  webapi-db:
    build:
      context: ./services/webapp/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres